"""initial schema

Revision ID: 6106833dd309
Revises: 
Create Date: 2026-01-20 17:43:35.145626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6106833dd309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_establishment', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_establishment'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availabilitys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_professional', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_professional'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedulings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id_user_client', sa.Integer(), nullable=False),
    sa.Column('id_professional', sa.Integer(), nullable=False),
    sa.Column('id_establishment', sa.Integer(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_establishment'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['id_professional'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['id_user_client'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_establishment_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['service_establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('id_scheduling', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_scheduling'], ['schedulings.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_scheduling')
    )
    op.create_table('service_schedulings',
    sa.Column('id_scheduling', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_scheduling'], ['schedulings.id'], ),
    sa.ForeignKeyConstraint(['id_service'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id_scheduling', 'id_service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_schedulings')
    op.drop_table('asessments')
    op.drop_table('services')
    op.drop_table('schedulings')
    op.drop_table('availabilitys')
    op.drop_table('verification_tokens')
    op.drop_table('professionals')
    op.drop_table('users')
    op.drop_table('establishments')
    # ### end Alembic commands ###
