"""create full database

Revision ID: 853b8be0b475
Revises: 0e4e84d6fc1e
Create Date: 2026-01-16 18:30:25.784977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853b8be0b475'
down_revision: Union[str, Sequence[str], None] = '0e4e84d6fc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_establishment', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_establishment'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_establishment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availabilitys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_professional', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_professional'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedulings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id_user_client', sa.Integer(), nullable=False),
    sa.Column('id_professional', sa.Integer(), nullable=False),
    sa.Column('id_establishment', sa.Integer(), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_establishment'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['id_professional'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['id_user_client'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('id_scheduling', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_scheduling'], ['schedulings.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_scheduling')
    )
    op.create_table('service_schedulings',
    sa.Column('id_scheduling', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_scheduling'], ['schedulings.id'], ),
    sa.ForeignKeyConstraint(['id_service'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id_scheduling', 'id_service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_schedulings')
    op.drop_table('asessments')
    op.drop_table('schedulings')
    op.drop_table('availabilitys')
    op.drop_table('services')
    op.drop_table('professionals')
    op.drop_table('establishments')
    # ### end Alembic commands ###
