"""initial database

Revision ID: b1dc2663e4b1
Revises: dcb952de8f0a
Create Date: 2026-01-26 14:40:00.193124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1dc2663e4b1'
down_revision: Union[str, Sequence[str], None] = 'dcb952de8f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'establishments', ['name'])
    op.create_unique_constraint(None, 'establishments', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'establishments', type_='unique')
    op.drop_constraint(None, 'establishments', type_='unique')
    # ### end Alembic commands ###
