"""create users table

Revision ID: dcb952de8f0a
Revises: a54173182008
Create Date: 2026-01-23 11:33:45.353136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb952de8f0a'
down_revision: Union[str, Sequence[str], None] = 'a54173182008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_schedulings')
    op.add_column('schedulings', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'schedulings', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedulings', type_='foreignkey')
    op.drop_column('schedulings', 'service_id')
    op.create_table('service_schedulings',
    sa.Column('id_scheduling', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_service', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_scheduling'], ['schedulings.id'], name=op.f('service_schedulings_id_scheduling_fkey')),
    sa.ForeignKeyConstraint(['id_service'], ['services.id'], name=op.f('service_schedulings_id_service_fkey')),
    sa.PrimaryKeyConstraint('id_scheduling', 'id_service', name=op.f('service_schedulings_pkey'))
    )
    # ### end Alembic commands ###
